# Generated by Django 6.0 on 2025-12-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsl', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='event',
            constraint=models.UniqueConstraint(fields=('resource', 'name', 'published_at', 'link'), name='unique_event'),
        ),
    ]
