# Generated by Django 6.0 on 2025-12-31 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsl', '0002_event_unique_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
