# Generated by Django 6.0 on 2026-01-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rmsl', '0003_event_scheduled_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_posted',
            field=models.BooleanField(default=False),
        ),
    ]
